console.log("Bem vindo ao Sistema Operacional NexusPlay")
console.log("Antes de começarmos precisamos de alguns dados")
let nome = prompt("digite seu nome:" )
console.log("Olá",nome,"Boa tarde")
let idade = prompt("Digite sua idade: ")
let email = prompt("Digite seu email: ")
let escola = prompt("Onde você estuda?")
let sala = prompt("Qual sua sala? ")
let professor = prompt("Qual seu professor?")
console.log("Olá",nome,"da escola",escola,"você estuda na sala",sala,"e tem",idade,"anos e seu email é",email,"se empenhe bastante para orgulhar o",professor)
console.log("Dados coletados, iniciando sistema")
